nmeum/android-tools

.github/workflows/build.yml
clang-11 only seems to pull in libstdc++-9-dev, not libstdc++-10-dev.
The former does not seem to have <span> causing the following
compilation error:
In file included from ../vendor/adb/client/file_sync_client.cpp:46:
../vendor/adb/compression_utils.h:21:10: fatal error: 'span' file not found
#include <span>
=> .github: Attempt to fix ubuntu 20.04 clang build

completions/CMakeLists.txt, completions/zsh/CMakeLists.txt, completions/zsh/adb.in, completions/zsh/fastboot.in
Technically, we no longer need to install the common completion file now
as we are only using this file for bash completions. However, this issue
is a blocker for the upcoming platform-tools-31.0.2 release and I don't
want to spend a lot of time fiddling with completion files at this
point in time. The completion setup can still be cleanup up later.
Fixes #38
=> completions: Remove zsh completion files

README.md, patches/extras/0002-libjsonpbparse-Fix-build-after-protobuf-util-Status-.patch, patches/extras/0003-lpadd-Add-missing-header-for-strerror.patch, vendor/CMakeLists.libbase.txt, vendor/CMakeLists.partition.txt, vendor/CMakeLists.sparse.txt, vendor/CMakeLists.txt
This PR adds tools to handle dynamic partitions (super.img), tested working on archlinux.
=> Add Dynamic Partition Tools

README.md, vendor/CMakeLists.mkbootimg.txt, vendor/CMakeLists.txt
Install the already existing (in tree) `mkbootimg`, `unpack_bootimg` and `repack_bootimg` Python scripts as executables.
Any thoughts? Seems to work fine for me locally as tested on Void Linux :)
=> Add boot.img manipulation tools

patches/adb/0021-tls-include-functional.patch, patches/boringssl/0012-CMakeLists.txt-Disable-Werror-by-default.patch, patches/selinux/0002-libselinux-store_stem-do-not-free-possible-non-heap-.patch
=> Fix compilation with GCC 12.1

patches/boringssl/0012-Add-support-for-RISC-V-64-bit-architecture.patch
Hi! I'm building this package for ArchLinux RISC-V distribution and I get an error message:
```
-- Checking for module 'libunwind-generic'
--   Package 'libunwind-generic', required by 'virtual:world', not found
libunwind not found. Disabling unwind tests.
CMake Error at vendor/boringssl/CMakeLists.txt:502 (message):
Unknown processor:riscv64
```
`boringssl` has supported RISC-V 64 architecture in [this commit](https://boringssl.googlesource.com/boringssl/+/4566bb5fe517f7f141b5fe935c559fc4311af35d). This PR brings it to the patch set of this package to support compiling it for RISC-V 64 architecture.
And since `git am` doesn't support fuzzy patching, this patch cannot be applied by `git am` directly, I replaced it with `patch` command, it shouldn't ruin the previous work, and avoid …
=> boringssl: Add support for RISC-V 64-bit architecture

CMakeLists.txt, vendor/CMakeLists.txt
* Set language standard via `CMAKE_C_STANDARD` and `CMAKE_CXX_STANDARD` standard
* Use new [`add_compile_options`](https://cmake.org/cmake/help/latest/command/add_compile_options.html) and [`add_compile_definitions`](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html)
* Instead of modifying both C and C++ flags directly
* Bump required CMake version to >= 3.12
=> Minor cmake cleanup

.gitmodules, README.md, vendor/CMakeLists.libufdt.txt, vendor/CMakeLists.txt
This is a tool for packing multiple DTB/DTBO files into a single image which is used by bootloader on various Android devices since circa 2017.
`libufdt` is now tracking tag [`platform-tools-33.0.3`](https://android.googlesource.com/platform/system/libufdt/+/refs/tags/platform-tools-33.0.3) as #65 has been merged.
=> Add mkdtboimg tool

vendor/CMakeLists.mkbootimg.txt
It now requires an import of a `gki/generate_gki_certificate.py`, so install the scripts in `/usr/share/android-tools/mkbootimg` and symlink back to `/usr/bin/mkbootimg` to avoid having to patch anything.
Suggestions for a better way to create the symlink are welcome, I'm not entirely happy with it, but it does work :)
Fixes #76.
=> Fix mkbootimg since 33.0.3 upgrade

README.md, vendor/CMakeLists.avb.txt, vendor/CMakeLists.txt
It's also an additional requirement to use the (already deprecated?!) [GKI 2.0 signing arguments](https://android.googlesource.com/platform/system/tools/mkbootimg/+/339274e/mkbootimg.py#555) with `mkbootimg`.
Fixes #77.
=> Add avbtool for working with Android Verified Boot

.github/workflows/build.yml
openSUSE Leap 15.3 is expected to be maintained until end of November 2022
=> CI: Switch to opensuse/leap:15.4

.github/workflows/build.yml
Fedora builds android-tools package using this repository. https://src.fedoraproject.org/rpms/android-tools
=> CI: Add Fedora in build matrix

patches/adb/0023-Update-usage-of-usbdevfs_urb-to-match-new-kernel-UAP.patch
The change is currently under review with AOSP team https://android-review.googlesource.com/c/platform/packages/modules/adb/+/2247053
There is another possible fix here https://android-review.googlesource.com/c/platform/packages/modules/adb/+/2241851
Fixes #74
=> Pull a fix for Linux 6.0 API changes

vendor/CMakeLists.txt
See [`.gitmodules`](https://github.com/nmeum/android-tools/blob/master/.gitmodules).
=> vendor: add mkbootimg & libufdt to android-vendored variable

vendor/CMakeLists.fastboot.txt, vendor/CMakeLists.mke2fs.txt, vendor/CMakeLists.txt
Changes:
* Revert some hunks from a1ab35b31525966e0f0770047cd82accb36d025b commit.
* Only add common sources from libselinux_defaults and libselinux.
* Define BUILD_HOST instead of HOST, see libselinux/Android.bp.
* use pkgconfig for pcre2-8 library.
=> Enable e2fsdroid in MacOS

.github/workflows/build.yml
* Changes:
- Linux docker and macos builds now depend on upload-src job.
- Download the source tarball from upload-src instead of checking out.
- Install tar and xz in fedora and opensuse.
* Pros:
- Now submodules are cloned only once.
- This reduces total CI time.
- Building from the released source tarball verifies it.
=> CI: Use source tarball instead of cloning submodules

.github/workflows/build.yml, patches/core/0012-libutils-Fix-missing-definition-of-shared_ptr-and-un.patch, patches/native/0001-Don-t-use-the-internal-glibc-header-sys-cdefs.h.patch, vendor/CMakeLists.fastboot.txt
Changes:
* Add install path in CI.
* Update patch in patches/native.
* Add upstream patch in patches/core.
* Define HAVE_REALLOCARRAY macro for libsepol in Linux.
=> Update submodules to version 33.0.3

vendor/CMakeLists.fastboot.txt
It is same as liblp and that name is officially used with fastboot. See https://android.googlesource.com/platform/system/core.git/+/refs/tags/platform-tools-33.0.3/fastboot/Android.bp
=> cmake: Remove redundant libfsmgr library

CMakeLists.txt
```
CMake Warning (dev) at CMakeLists.txt:1 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
```
=> CMake: Fix cmake_minimum_required() call location warning

CMakeLists.txt
```
This excludes files with .apk, .html, .pdf, .png extensions.
Also write the values as a list to make things more clear.
```
=> CMake: Exclude more blobs in generated source tarball

patches/extras/0002-libjsonpbparse-Fix-build-after-protobuf-util-Status-.patch, vendor/CMakeLists.adb.txt, vendor/CMakeLists.partition.txt, vendor/CMakeLists.txt
Fixes https://github.com/nmeum/android-tools/issues/119
=> vendor/extras: Fix building with newer protobuf versions

.github/workflows/build.yml
Required for services that do not allow network access to the outside during compilation (e.g. open build service etc.). When compiling, at least an `export GOFLAGS="-mod=vendor"` must be done before.
See https://github.com/nmeum/android-tools/issues/47
=> Include go vendor modules for boringssl

.github/workflows/build.yml, vendor/CMakeLists.f2fstools.txt, vendor/CMakeLists.mke2fs.txt, vendor/CMakeLists.txt
Fixes https://github.com/nmeum/android-tools/issues/109
```
make_f2fs tool is reqired by fastboot. If the make_f2fs executable is
not present the following error is shown.
$ fastboot format:f2fs userdata
/usr/bin/make_f2fs failed with status 1
fastboot: error: Cannot generate image for userdata
This commit also splits libext2_uuid static library from libext2fs
```
=> CMake: Add make_f2fs tool for fastboot

.github/workflows/build.yml, vendor/CMakeLists.f2fstools.txt, vendor/CMakeLists.txt
Fixes https://github.com/nmeum/android-tools/issues/127
=> CMake: Add sload_f2fs tool

patches/adb/0025-Add-explicit-import-for-algorithm.patch, patches/core/0012-Add-explicit-import-for-algorithm.patch
By default GCC 14 no longer includes <algorithm>, so it has to be explicitly imported now.
=> Import <algorithm> to build on GCC 14

vendor/CMakeLists.txt
As per upstream guidance [0] we should compile the sources with this flag in order to not hit issues with using uninitialized variables.
[0] https://android-review.googlesource.com/c/platform/system/core/+/2963911/1#message-01ebff378bb51f7815b6ed8b035a57fbce0418ab
Fixes #133
=> CMake: Compile with -ftrivial-auto-var-init=zero

README.md
_Hello @nmeum,_
First of all, thank you for this great project! 🙇🏼
I noticed that some links are broken, so I'd like to help you update them.
These changes:
- fix broken links
- add a link to Repology
- replace `http` with `https`
- update links to Clang and Go
- add a direct link to @anatol's legacy project
_Best regards!_
=> 🐛 Fix broken links at README.md

.github/workflows/build.yml
* Do not uninstall openssl@1.1 to prevent various warnings.
* Remove only openssl include directory. /opt/homebrew/include/openssl
directory is present in macos-14 runner only.
* Add quiet option with brew install command to suppress some warnings as following.
brotli 1.1.0 is already installed and up-to-date. To reinstall 1.1.0, run: brew reinstall brotli
cmake 3.29.3 is already installed and up-to-date. To reinstall 3.29.3, run: brew reinstall cmake
etc.
* Change install prefix to HOME/android-tools because cmake
can not install in /usr/local directory in macos-14. The
error is as following.
CMake Error at completions/bash/cmake_install.cmake:49 (file):
file cannot create directory: /usr/local/share/bash-completion/completions.
Maybe need administrative privileges.
=> CI: Add macos-14 in build matrix

.github/workflows/build.yml, vendor/CMakeLists.adb.txt
=> CMake: Install adb man page

vendor/CMakeLists.mkbootimg.txt
I noticed that the absolute symlink did not work on my system.
While investigating I noticed that on SUSE the symlink gets relinked
to be relative to be relative to the install location of the symlink
after which the link works.
Using a relative link seems safer to me.
=> Don't use absolute dir for mkbootimg symlink

.github/workflows/build.yml, CMakeLists.txt, vendor/CMakeLists.txt
fmt library was added in vendor in 21061c1dfb006c22304053c1f6f9e48ae4cbe25a commit for systems with older fmt versions. Now, distributions can choose to link with their own fmt shared library or use the bundled one.
=> CMake: Add option to use system fmt library

.github/workflows/build.yml
This fixes the previous CI failure https://github.com/nmeum/android-tools/actions/runs/11862558771/job/33062200632
=> CI: Add protobuf-compiler dependency for ubuntu

.github/workflows/build.yml
macos-12 runner image will be fully retired by the December 3rd, 2024. https://github.blog/changelog/2024-08-19-notice-of-upcoming-deprecations-and-breaking-changes-in-github-actions-runners/
=> CI: Replace macos-12 with macos-15 due to deprecation

patches/adb/0023-Update-usage-of-usbdevfs_urb-to-match-new-kernel-UAP.patch, patches/core/0009-Don-t-use-the-internal-glibc-header-sys-cdefs.h.patch, patches/core/0011-core-include-missing-headers.patch, patches/libbase/0002-remove-glibc-internal-headers-cdefs.h.patch
Such patches may be technically invalid. These errors also mess with `git patch-id`, which is undesirable.
=> Fix missing whitespace in patches
